// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: J2KResultsHub.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VarResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellNumber uint32       `protobuf:"varint,1,opt,name=cellNumber,proto3" json:"cellNumber,omitempty"`
	VarResuls  []*VarResult `protobuf:"bytes,2,rep,name=varResuls,proto3" json:"varResuls,omitempty"`
}

func (x *VarResults) Reset() {
	*x = VarResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarResults) ProtoMessage() {}

func (x *VarResults) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarResults.ProtoReflect.Descriptor instead.
func (*VarResults) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{0}
}

func (x *VarResults) GetCellNumber() uint32 {
	if x != nil {
		return x.CellNumber
	}
	return 0
}

func (x *VarResults) GetVarResuls() []*VarResult {
	if x != nil {
		return x.VarResuls
	}
	return nil
}

// The result of a single variable of a specific cell
type VarResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarName    string `protobuf:"bytes,1,opt,name=varName,proto3" json:"varName,omitempty"`
	VarType    string `protobuf:"bytes,2,opt,name=varType,proto3" json:"varType,omitempty"`
	VarBytes   []byte `protobuf:"bytes,3,opt,name=varBytes,proto3" json:"varBytes,omitempty"`
	Available  bool   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"` // for ResultsHub internal use
	IsJson     bool   `protobuf:"varint,5,opt,name=isJson,proto3" json:"isJson,omitempty"`
	JsonString string `protobuf:"bytes,6,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
}

func (x *VarResult) Reset() {
	*x = VarResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarResult) ProtoMessage() {}

func (x *VarResult) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarResult.ProtoReflect.Descriptor instead.
func (*VarResult) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{1}
}

func (x *VarResult) GetVarName() string {
	if x != nil {
		return x.VarName
	}
	return ""
}

func (x *VarResult) GetVarType() string {
	if x != nil {
		return x.VarType
	}
	return ""
}

func (x *VarResult) GetVarBytes() []byte {
	if x != nil {
		return x.VarBytes
	}
	return nil
}

func (x *VarResult) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *VarResult) GetIsJson() bool {
	if x != nil {
		return x.IsJson
	}
	return false
}

func (x *VarResult) GetJsonString() string {
	if x != nil {
		return x.JsonString
	}
	return ""
}

type FetchVarResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarName         string `protobuf:"bytes,1,opt,name=varName,proto3" json:"varName,omitempty"`
	VarAncestorCell uint32 `protobuf:"varint,2,opt,name=varAncestorCell,proto3" json:"varAncestorCell,omitempty"`
}

func (x *FetchVarResultRequest) Reset() {
	*x = FetchVarResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVarResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVarResultRequest) ProtoMessage() {}

func (x *FetchVarResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVarResultRequest.ProtoReflect.Descriptor instead.
func (*FetchVarResultRequest) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{2}
}

func (x *FetchVarResultRequest) GetVarName() string {
	if x != nil {
		return x.VarName
	}
	return ""
}

func (x *FetchVarResultRequest) GetVarAncestorCell() uint32 {
	if x != nil {
		return x.VarAncestorCell
	}
	return 0
}

type WaitCellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaitFor uint32 `protobuf:"varint,1,opt,name=waitFor,proto3" json:"waitFor,omitempty"`
}

func (x *WaitCellRequest) Reset() {
	*x = WaitCellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitCellRequest) ProtoMessage() {}

func (x *WaitCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitCellRequest.ProtoReflect.Descriptor instead.
func (*WaitCellRequest) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{3}
}

func (x *WaitCellRequest) GetWaitFor() uint32 {
	if x != nil {
		return x.WaitFor
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{4}
}

// The request message containing the sender's ID and a message.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId string `protobuf:"bytes,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{5}
}

func (x *HelloRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HelloRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the reply.
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KResultsHub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_J2KResultsHub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_J2KResultsHub_proto_rawDescGZIP(), []int{6}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_J2KResultsHub_proto protoreflect.FileDescriptor

var file_J2KResultsHub_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x48, 0x75, 0x62, 0x22, 0x64, 0x0a, 0x0a, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x36, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x09, 0x76, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x09, 0x56,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x76, 0x61, 0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x76, 0x61, 0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4a, 0x73, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x5b,
	0x0a, 0x15, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x61, 0x72, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x43, 0x65, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x76, 0x61, 0x72, 0x41,
	0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x43, 0x65, 0x6c, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x57,
	0x61, 0x69, 0x74, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x77, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x77, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x44, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0xb5, 0x02, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x12, 0x46,
	0x0a, 0x11, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x65, 0x6c, 0x6c, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x48, 0x75, 0x62, 0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x14,
	0x2e, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x2e, 0x4a, 0x32, 0x4b, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x56,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x57, 0x61,
	0x69, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x4a, 0x32, 0x4b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x43, 0x65,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4a, 0x32, 0x4b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1b, 0x2e,
	0x4a, 0x32, 0x4b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x4a, 0x32, 0x4b,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x75, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_J2KResultsHub_proto_rawDescOnce sync.Once
	file_J2KResultsHub_proto_rawDescData = file_J2KResultsHub_proto_rawDesc
)

func file_J2KResultsHub_proto_rawDescGZIP() []byte {
	file_J2KResultsHub_proto_rawDescOnce.Do(func() {
		file_J2KResultsHub_proto_rawDescData = protoimpl.X.CompressGZIP(file_J2KResultsHub_proto_rawDescData)
	})
	return file_J2KResultsHub_proto_rawDescData
}

var file_J2KResultsHub_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_J2KResultsHub_proto_goTypes = []interface{}{
	(*VarResults)(nil),            // 0: J2KResultsHub.VarResults
	(*VarResult)(nil),             // 1: J2KResultsHub.VarResult
	(*FetchVarResultRequest)(nil), // 2: J2KResultsHub.FetchVarResultRequest
	(*WaitCellRequest)(nil),       // 3: J2KResultsHub.WaitCellRequest
	(*Empty)(nil),                 // 4: J2KResultsHub.Empty
	(*HelloRequest)(nil),          // 5: J2KResultsHub.HelloRequest
	(*HelloReply)(nil),            // 6: J2KResultsHub.HelloReply
}
var file_J2KResultsHub_proto_depIdxs = []int32{
	1, // 0: J2KResultsHub.VarResults.varResuls:type_name -> J2KResultsHub.VarResult
	0, // 1: J2KResultsHub.ResultsHub.ClaimCellFinished:input_type -> J2KResultsHub.VarResults
	2, // 2: J2KResultsHub.ResultsHub.FetchVarResult:input_type -> J2KResultsHub.FetchVarResultRequest
	3, // 3: J2KResultsHub.ResultsHub.WaitForCell:input_type -> J2KResultsHub.WaitCellRequest
	5, // 4: J2KResultsHub.ResultsHub.SayHello:input_type -> J2KResultsHub.HelloRequest
	4, // 5: J2KResultsHub.ResultsHub.ClaimCellFinished:output_type -> J2KResultsHub.Empty
	1, // 6: J2KResultsHub.ResultsHub.FetchVarResult:output_type -> J2KResultsHub.VarResult
	4, // 7: J2KResultsHub.ResultsHub.WaitForCell:output_type -> J2KResultsHub.Empty
	6, // 8: J2KResultsHub.ResultsHub.SayHello:output_type -> J2KResultsHub.HelloReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_J2KResultsHub_proto_init() }
func file_J2KResultsHub_proto_init() {
	if File_J2KResultsHub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_J2KResultsHub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchVarResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitCellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KResultsHub_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_J2KResultsHub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_J2KResultsHub_proto_goTypes,
		DependencyIndexes: file_J2KResultsHub_proto_depIdxs,
		MessageInfos:      file_J2KResultsHub_proto_msgTypes,
	}.Build()
	File_J2KResultsHub_proto = out.File
	file_J2KResultsHub_proto_rawDesc = nil
	file_J2KResultsHub_proto_goTypes = nil
	file_J2KResultsHub_proto_depIdxs = nil
}
