// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: J2KSerializer.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VarResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarResults []*VarResults `protobuf:"bytes,1,rep,name=varResults,proto3" json:"varResults,omitempty"`
}

func (x *VarResults) Reset() {
	*x = VarResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarResults) ProtoMessage() {}

func (x *VarResults) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarResults.ProtoReflect.Descriptor instead.
func (*VarResults) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{0}
}

func (x *VarResults) GetVarResults() []*VarResults {
	if x != nil {
		return x.VarResults
	}
	return nil
}

// The result of a single variable of a specific cell
type VarResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarName   string    `protobuf:"bytes,1,opt,name=varName,proto3" json:"varName,omitempty"`
	VarType   string    `protobuf:"bytes,2,opt,name=varType,proto3" json:"varType,omitempty"`
	VarValye  *VarValue `protobuf:"bytes,3,opt,name=varValye,proto3" json:"varValye,omitempty"`
	Available bool      `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"` // for serializer internal use
}

func (x *VarResult) Reset() {
	*x = VarResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarResult) ProtoMessage() {}

func (x *VarResult) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarResult.ProtoReflect.Descriptor instead.
func (*VarResult) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{1}
}

func (x *VarResult) GetVarName() string {
	if x != nil {
		return x.VarName
	}
	return ""
}

func (x *VarResult) GetVarType() string {
	if x != nil {
		return x.VarType
	}
	return ""
}

func (x *VarResult) GetVarValye() *VarValue {
	if x != nil {
		return x.VarValye
	}
	return nil
}

func (x *VarResult) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type VarValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*VarValue_BoolValue
	//	*VarValue_Int32Value
	//	*VarValue_Int64Value
	//	*VarValue_Uint32Value
	//	*VarValue_Uint64Value
	//	*VarValue_FloatValue
	//	*VarValue_DoubleValue
	//	*VarValue_StringValue
	//	*VarValue_BytesValue
	Value isVarValue_Value `protobuf_oneof:"value"`
}

func (x *VarValue) Reset() {
	*x = VarValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarValue) ProtoMessage() {}

func (x *VarValue) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarValue.ProtoReflect.Descriptor instead.
func (*VarValue) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{2}
}

func (m *VarValue) GetValue() isVarValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *VarValue) GetBoolValue() bool {
	if x, ok := x.GetValue().(*VarValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *VarValue) GetInt32Value() int32 {
	if x, ok := x.GetValue().(*VarValue_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *VarValue) GetInt64Value() int64 {
	if x, ok := x.GetValue().(*VarValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *VarValue) GetUint32Value() uint32 {
	if x, ok := x.GetValue().(*VarValue_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *VarValue) GetUint64Value() uint64 {
	if x, ok := x.GetValue().(*VarValue_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *VarValue) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*VarValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *VarValue) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*VarValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *VarValue) GetStringValue() string {
	if x, ok := x.GetValue().(*VarValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *VarValue) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*VarValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

type isVarValue_Value interface {
	isVarValue_Value()
}

type VarValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type VarValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type VarValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type VarValue_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,4,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type VarValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type VarValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type VarValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type VarValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type VarValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*VarValue_BoolValue) isVarValue_Value() {}

func (*VarValue_Int32Value) isVarValue_Value() {}

func (*VarValue_Int64Value) isVarValue_Value() {}

func (*VarValue_Uint32Value) isVarValue_Value() {}

func (*VarValue_Uint64Value) isVarValue_Value() {}

func (*VarValue_FloatValue) isVarValue_Value() {}

func (*VarValue_DoubleValue) isVarValue_Value() {}

func (*VarValue_StringValue) isVarValue_Value() {}

func (*VarValue_BytesValue) isVarValue_Value() {}

type FetchVarResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarName       string  `protobuf:"bytes,1,opt,name=varName,proto3" json:"varName,omitempty"`
	AncestorCells []int32 `protobuf:"varint,2,rep,packed,name=ancestorCells,proto3" json:"ancestorCells,omitempty"`
}

func (x *FetchVarResultRequest) Reset() {
	*x = FetchVarResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVarResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVarResultRequest) ProtoMessage() {}

func (x *FetchVarResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVarResultRequest.ProtoReflect.Descriptor instead.
func (*FetchVarResultRequest) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{3}
}

func (x *FetchVarResultRequest) GetVarName() string {
	if x != nil {
		return x.VarName
	}
	return ""
}

func (x *FetchVarResultRequest) GetAncestorCells() []int32 {
	if x != nil {
		return x.AncestorCells
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{4}
}

// The request message containing the sender's ID and a message.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId string `protobuf:"bytes,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{5}
}

func (x *HelloRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HelloRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the reply.
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_J2KSerializer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_J2KSerializer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_J2KSerializer_proto_rawDescGZIP(), []int{6}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_J2KSerializer_proto protoreflect.FileDescriptor

var file_J2KSerializer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x0a, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x92, 0x01,
	0x0a, 0x09, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x33, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x79, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x72, 0x2e, 0x56, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72, 0x56,
	0x61, 0x6c, 0x79, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0xd4, 0x02, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b,
	0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a,
	0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x57, 0x0a, 0x15, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x43, 0x65, 0x6c,
	0x6c, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x44, 0x0a, 0x0c, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf1, 0x01, 0x0a, 0x0d, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x43, 0x65, 0x6c, 0x6c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x12, 0x19, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x2e, 0x56, 0x61, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x14, 0x2e, 0x4a, 0x32,
	0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x61, 0x72, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4a, 0x32,
	0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x56, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x1b, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x4a, 0x32, 0x4b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_J2KSerializer_proto_rawDescOnce sync.Once
	file_J2KSerializer_proto_rawDescData = file_J2KSerializer_proto_rawDesc
)

func file_J2KSerializer_proto_rawDescGZIP() []byte {
	file_J2KSerializer_proto_rawDescOnce.Do(func() {
		file_J2KSerializer_proto_rawDescData = protoimpl.X.CompressGZIP(file_J2KSerializer_proto_rawDescData)
	})
	return file_J2KSerializer_proto_rawDescData
}

var file_J2KSerializer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_J2KSerializer_proto_goTypes = []interface{}{
	(*VarResults)(nil),            // 0: J2KSerializer.VarResults
	(*VarResult)(nil),             // 1: J2KSerializer.VarResult
	(*VarValue)(nil),              // 2: J2KSerializer.VarValue
	(*FetchVarResultRequest)(nil), // 3: J2KSerializer.FetchVarResultRequest
	(*Empty)(nil),                 // 4: J2KSerializer.Empty
	(*HelloRequest)(nil),          // 5: J2KSerializer.HelloRequest
	(*HelloReply)(nil),            // 6: J2KSerializer.HelloReply
}
var file_J2KSerializer_proto_depIdxs = []int32{
	0, // 0: J2KSerializer.VarResults.varResults:type_name -> J2KSerializer.VarResults
	2, // 1: J2KSerializer.VarResult.varValye:type_name -> J2KSerializer.VarValue
	0, // 2: J2KSerializer.BrokerService.ClaimCellFinished:input_type -> J2KSerializer.VarResults
	3, // 3: J2KSerializer.BrokerService.FetchVarResult:input_type -> J2KSerializer.FetchVarResultRequest
	5, // 4: J2KSerializer.BrokerService.SayHello:input_type -> J2KSerializer.HelloRequest
	4, // 5: J2KSerializer.BrokerService.ClaimCellFinished:output_type -> J2KSerializer.Empty
	1, // 6: J2KSerializer.BrokerService.FetchVarResult:output_type -> J2KSerializer.VarResult
	6, // 7: J2KSerializer.BrokerService.SayHello:output_type -> J2KSerializer.HelloReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_J2KSerializer_proto_init() }
func file_J2KSerializer_proto_init() {
	if File_J2KSerializer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_J2KSerializer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchVarResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_J2KSerializer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_J2KSerializer_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*VarValue_BoolValue)(nil),
		(*VarValue_Int32Value)(nil),
		(*VarValue_Int64Value)(nil),
		(*VarValue_Uint32Value)(nil),
		(*VarValue_Uint64Value)(nil),
		(*VarValue_FloatValue)(nil),
		(*VarValue_DoubleValue)(nil),
		(*VarValue_StringValue)(nil),
		(*VarValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_J2KSerializer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_J2KSerializer_proto_goTypes,
		DependencyIndexes: file_J2KSerializer_proto_depIdxs,
		MessageInfos:      file_J2KSerializer_proto_msgTypes,
	}.Build()
	File_J2KSerializer_proto = out.File
	file_J2KSerializer_proto_rawDesc = nil
	file_J2KSerializer_proto_goTypes = nil
	file_J2KSerializer_proto_depIdxs = nil
}
